server:
  servlet:
  #  å®šä¹‰é¡¹ç›®çš„è®¿é—®è®¿é—®è·¯å¾?
    context-path: /consumer
    #å®šä¹‰ç«¯å£å?
  port: 7002
spring:
  redis:
    cluster:
      #è®¾ç½®keyçš„ç”Ÿå­˜æ—¶é—´ï¼Œå½“keyè¿‡æœŸæ—¶ï¼Œå®ƒä¼šè¢«è‡ªåŠ¨åˆ é™¤ï¼›
      expire-seconds: 120
      #è®¾ç½®å‘½ä»¤çš„æ‰§è¡Œæ—¶é—´ï¼Œå¦‚æœè¶…è¿‡è¿™ä¸ªæ—¶é—´ï¼Œåˆ™æŠ¥é”™;
      command-timeout: 5000
      #è®¾ç½®redisé›†ç¾¤çš„èŠ‚ç‚¹ä¿¡æ¯ï¼Œå…¶ä¸­namenodeä¸ºåŸŸåè§£æï¼Œé€šè¿‡è§£æåŸŸåæ¥è·å–ç›¸åº”çš„åœ°å€;
      nodes: namenode22:6379,datanode23:6379,datanode24:6379,datanode25:6379,datanode26:6379,datanode27:6379
  application:
  #å®šä¹‰åº”ç”¨åç§°ï¼Œå³æœåŠ¡åç§°
    name: consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka
